[tool.isort]
line_length = 90
length_sort = true
multi_line_output = 5
use_parentheses = true
lines_after_imports = 2
force_sort_within_sections = true
# For more confits visit https://pycqa.github.io/isort/docs/configuration/options.html


[tool.autopep8]
max_line_length = 80
ignore = ["E266", "E501", "W503", "W504", "E704", "W505", "W6", "E402"]
# E266 Too many leading # for block comment
# E501 Line too long (80 > 79 characters)
# W503 Line break before binary operator
# W504 Line break after binary operator
# E704 Multiple statements on one line (def)
# W505 doc line too long (80 > 79 characters)
# E402 All import statements at the top of a file